#spring.application.name=demo
#
#spring.profiles.active=local
#
#spring.jpa.hibernate.ddl-auto=update
#
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#
#spring.h2.console.enabled=false
#
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=gafoor11@gmail.com
#spring.mail.password=123456789
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.connectiontimeout=5000
#spring.mail.properties.mail.smtp.timeout=5000
#spring.mail.properties.mail.smtp.writetimeout=5000
#razorpay.key.id=provide your razorpay key id
#razorpay.key.secret=provide your razorpay secret key
#razorpay.callback.base-url=http://localhost:5173
#stripe.secret.key=${STRIPE_SECRET_KEY:}
#stripe.callback.base-url=${STRIPE_CALLBACK_BASE_URL:http://localhost:5173}
#stripe.success-url=${STRIPE_SUCCESS_URL:http://localhost:3000/success}
#stripe.cancel-url=${STRIPE_CANCEL_URL:http://localhost:3000/cancel}



spring.application.name=demo

spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.h2.console.enabled=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gafoor11@gmail.com
spring.mail.password=123456789
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

#razorpay.key.id=provide your razorpay key id
#razorpay.key.secret=provide your razorpay secret key
#razorpay.callback.base-url=http://localhost:5173

#stripe.secret.key=sk_test_your_actual_key_here
#stripe.callback.base-url=http://localhost:5173
#stripe.success-url=http://localhost:5173/success
#stripe.cancel-url=http://localhost:5173/cancel